import fs from 'fs';
import path from 'path';

test('主 Agent 正文与 commentary 复用同一个流式节奏器', () => {
  const chatSource = fs.readFileSync(path.resolve(__dirname, './useCenterChat.ts'), 'utf8');
  const streamSource = fs.readFileSync(path.resolve(__dirname, './smoothStreamText.ts'), 'utf8');
  const processSource = fs.readFileSync(path.resolve(__dirname, './harnessProcessStreams.ts'), 'utf8');
  const apiSource = fs.readFileSync(path.resolve(__dirname, '../agentApi.ts'), 'utf8');
  const messageListSource = fs.readFileSync(path.resolve(__dirname, '../components/MessageList.vue'), 'utf8');

  expect(chatSource).toContain("import { createSmoothStreamText } from './smoothStreamText';");
  expect(chatSource).toContain('return createSmoothStreamText({');
  expect(chatSource).toContain("from './harnessProcessStreams'");
  expect(processSource).toContain('function createCommentaryStream<');
  expect(processSource).toContain('function createReasoningStream<');
  expect(chatSource).toContain('commentaryStream.show(text, kind)');
  expect(processSource).toContain('void stream.finish(clean)');
  expect(processSource).not.toContain('return stream.finish(clean)');
  expect(chatSource).toContain('return reasoningStream.complete(payload)');
  expect(chatSource).not.toContain('await waitForStreamPaint()');
  expect(processSource).not.toContain('await painter.finish');
  expect(chatSource).not.toContain('window.requestAnimationFrame(() => window.requestAnimationFrame');
  expect(streamSource).toContain('requestFrame: requestStreamAnimationFrame');
  expect(streamSource).toContain('cancelFrame: cancelStreamAnimationFrame');
  expect(streamSource).toContain('SMOOTH_STREAM_FINISH_MIN_MS = 700');
  expect(streamSource).toContain('SMOOTH_STREAM_FINISH_MAX_MS = 2000');
  expect(processSource).toContain('commentary 与最终正文共用 smoothStreamText 默认速度');
  expect(processSource).toContain('applyReasoningDelta(target');
  expect(processSource).toContain('parkTransientReasoning(target');
  expect(chatSource.match(/applyCommentaryAndHidePlanBody\(/g)?.length).toBe(4);
  expect(apiSource).toContain('await cb.onCommentary?.(text, content');
  expect(apiSource).toContain('await cb.onReasoningCompleted?.({');
  expect(apiSource).toContain("await appendPayload(trimmed.replace(/^data:\\s*/, ''))");
  expect(messageListSource).toMatch(/\.message-list\s*\{[\s\S]*?padding:\s*36px\s+0\s+148px/);
  expect(streamSource).toContain('SMOOTH_STREAM_FRAME_MS = 1000 / 60');
  expect(streamSource).toContain('scheduler.requestFrame(paint)');
  expect(streamSource).toContain('BASE_CHARS_PER_SECOND + backlog * BACKLOG_RATE_GAIN');
  expect(streamSource).toContain("window.matchMedia('(prefers-reduced-motion: reduce)')");
  expect(streamSource).not.toContain('setInterval');
});
