from app.services.chat.builtin_assistants.registry import (
    CAMPUS_APP_ID,
    CAMPUS_IDENTITY,
    CAMPUS_PRESET,
    CAMPUS_THREAD_ORIGIN,
    PRESENTATION_APP_ID,
    PRESENTATION_IDENTITY,
    PRESENTATION_PRESET,
    PRESENTATION_THREAD_ORIGIN,
    get_builtin_assistant_by_id,
    get_builtin_assistant_by_preset,
    is_builtin_assistant_id,
    is_campus_preset,
    is_presentation_preset,
    is_supported_preset,
    origin_for_preset,
    preset_from_thread_origin,
)

__all__ = [
    "CAMPUS_APP_ID",
    "CAMPUS_IDENTITY",
    "CAMPUS_PRESET",
    "CAMPUS_THREAD_ORIGIN",
    "PRESENTATION_APP_ID",
    "PRESENTATION_IDENTITY",
    "PRESENTATION_PRESET",
    "PRESENTATION_THREAD_ORIGIN",
    "get_builtin_assistant_by_id",
    "get_builtin_assistant_by_preset",
    "is_builtin_assistant_id",
    "is_campus_preset",
    "is_presentation_preset",
    "is_supported_preset",
    "origin_for_preset",
    "preset_from_thread_origin",
]
