"""AXIOM main-chat Agent Harness and its canonical contracts."""

from .contracts import (
    AppliedToolResultPolicy,
    AgentMode,
    ApprovalPolicy,
    EffectScope,
    ExecutionProfileId,
    EventEnvelope,
    ObservationStatus,
    PlanSnapshot,
    PlanStepSnapshot,
    PlanStepStatus,
    ResultSizePolicy,
    RunPhase,
    RunSnapshot,
    ToolCallContext,
    ToolObservation,
    ToolRequest,
    ToolSpec,
)
from .event_catalog import EVENT_CATALOG, event_definition, validate_event
from .dispatcher import RegisteredTool, ToolDispatcher, ToolRegistry
from .completion import CompletionClaim, CompletionDecision, CompletionVerifier
from .context import (
    CompiledContext,
    ContextCompiler,
    ContextFacts,
    ContextProjectionLedger,
    ContextSnapshot,
    ProjectedThreadContext,
    ProjectedContext,
    StableBasePrompt,
    ThreadContextProjectionLedger,
    ThreadWorldState,
)
from .kernel import HarnessKernel
from .memory import (
    MemoryCandidate,
    MemoryController,
    MemoryDecision,
    MemoryGrounding,
    MemoryStability,
)
from .policy import HarnessPolicy, PolicyDecision
from .plan_store import PlanConflict, revise_goal, update_plan
from .profiles import HarnessProfile, get_profile
from .results import (
    ObservationCompactor,
    ProjectedToolResult,
    ResultStore,
    ToolResultProjector,
    apply_projection_to_execution_result,
    apply_projection_to_observation,
    most_restrictive_result_policy,
)
from .tool_result_store import (
    DurableToolResultRef,
    DurableToolResultStore,
    ToolResultPage,
    render_tool_result_page,
)
from .model_usage_audit import (
    LogicalModelCall,
    ModelCallPolicy,
    NormalizedProviderUsage,
    ProviderAttemptHandle,
    ProviderAttemptOutcome,
    ProviderCallPurpose,
)
from .model_usage_report import RootUsageAggregate

__all__ = [
    "AgentMode",
    "AppliedToolResultPolicy",
    "ApprovalPolicy",
    "CompiledContext",
    "CompletionClaim",
    "CompletionDecision",
    "CompletionVerifier",
    "ContextCompiler",
    "ContextFacts",
    "ContextProjectionLedger",
    "ContextSnapshot",
    "ProjectedThreadContext",
    "EffectScope",
    "ExecutionProfileId",
    "EVENT_CATALOG",
    "EventEnvelope",
    "HarnessProfile",
    "HarnessKernel",
    "HarnessPolicy",
    "MemoryCandidate",
    "MemoryController",
    "MemoryDecision",
    "MemoryGrounding",
    "MemoryStability",
    "LogicalModelCall",
    "ModelCallPolicy",
    "NormalizedProviderUsage",
    "ObservationStatus",
    "ObservationCompactor",
    "PlanSnapshot",
    "PlanConflict",
    "PlanStepSnapshot",
    "PlanStepStatus",
    "PolicyDecision",
    "ProjectedContext",
    "StableBasePrompt",
    "ThreadContextProjectionLedger",
    "ThreadWorldState",
    "ProjectedToolResult",
    "ProviderAttemptHandle",
    "ProviderAttemptOutcome",
    "ProviderCallPurpose",
    "RegisteredTool",
    "ResultSizePolicy",
    "DurableToolResultRef",
    "DurableToolResultStore",
    "RunPhase",
    "RootUsageAggregate",
    "RunSnapshot",
    "ResultStore",
    "ToolResultPage",
    "ToolResultProjector",
    "apply_projection_to_execution_result",
    "apply_projection_to_observation",
    "ToolCallContext",
    "ToolObservation",
    "ToolRequest",
    "ToolDispatcher",
    "ToolRegistry",
    "ToolSpec",
    "event_definition",
    "get_profile",
    "validate_event",
    "revise_goal",
    "update_plan",
    "most_restrictive_result_policy",
    "render_tool_result_page",
]
