export const translations:any = {
    // Labels
    'Activate the global connect tool': '激活全局连接工具',
    'Append {type}': '添加 {type}',
    'Append Task': '添加任务',
    'Append Gateway': '添加网关',
    'Append EndEvent': '添加结束事件',
    'Append StartEvent': '添加开始事件',
    "Append Intermediate/Boundary Event": '添加边界事件',
    'Add Lane above': '在上面添加道',
    'Divide into two Lanes': '分割成两个道',
    'Divide into three Lanes': '分割成三个道',
    'Add Lane below': '在下面添加道',
    'Append compensation activity': '追加补偿活动',
    'Change type': '修改类型',
    'Connect using Association': '使用关联连接',
    'Connect using Sequence/MessageFlow or Association': '使用顺序/消息流或者关联连接',
    'Connect using DataInputAssociation': '使用数据输入关联连接',
    'Remove': '移除',
    'Activate hand tool': '激活抓手工具',
    'Activate lasso tool': '激活套索工具',
    'Activate create/remove space tool': '激活创建/删除空间工具',
    'Create expanded SubProcess': '创建扩展子过程',
    'Create IntermediateThrowEvent/BoundaryEvent': '创建中间抛出事件/边界事件',
    'Create Pool/Participant': '创建池/参与者',
    'Parallel Multi Instance': '并行多重事件',
    'Sequential Multi Instance': '时序多重事件',
    'DataObjectReference': '数据对象参考',
    'DataStoreReference': '数据存储参考',
    'Loop': '循环',
    'Ad-hoc': '即席',
    'Create {type}': '创建 {type}',
    'Task': '任务',
    'Send Task': '发送任务',
    'Receive Task': '接收任务',
    'User Task': '用户任务',
    'User task': '用户任务',
    'Manual Task': '手工任务',
    'Business Rule Task': '业务规则任务',
    'Service Task': '服务任务',
    'Script Task': '脚本任务',
    'Call Activity': '调用活动',
    'Sub Process (collapsed)': '子流程（折叠的）',
    'Sub Process (expanded)': '子流程（展开的）',
    'Start Event': '开始事件',
    'StartEvent': '开始事件',
    'Intermediate Throw Event': '中间事件',
    'End Event': '结束事件',
    'EndEvent': '结束事件',
    'Create Gateway': '创建网关',
    'Create Intermediate/Boundary Event': '创建中间/边界事件',
    'Message Start Event': '消息开始事件',
    'Timer Start Event': '定时开始事件',
    'Conditional Start Event': '条件开始事件',
    'Signal Start Event': '信号开始事件',
    'Error Start Event': '错误开始事件',
    'Escalation Start Event': '升级开始事件',
    'Compensation Start Event': '补偿开始事件',
    'Message Start Event (non-interrupting)': '消息开始事件（非中断）',
    'Timer Start Event (non-interrupting)': '定时开始事件（非中断）',
    'Conditional Start Event (non-interrupting)': '条件开始事件（非中断）',
    'Signal Start Event (non-interrupting)': '信号开始事件（非中断）',
    'Escalation Start Event (non-interrupting)': '升级开始事件（非中断）',
    'Message Intermediate Catch Event': '消息中间捕获事件',
    'Message Intermediate Throw Event': '消息中间抛出事件',
    'Timer Intermediate Catch Event': '定时中间捕获事件',
    'Escalation Intermediate Throw Event': '升级中间抛出事件',
    'Conditional Intermediate Catch Event': '条件中间捕获事件',
    'Link Intermediate Catch Event': '链接中间捕获事件',
    'Link Intermediate Throw Event': '链接中间抛出事件',
    'Compensation Intermediate Throw Event': '补偿中间抛出事件',
    'Signal Intermediate Catch Event': '信号中间捕获事件',
    'Signal Intermediate Throw Event': '信号中间抛出事件',
    'Message End Event': '消息结束事件',
    'Escalation End Event': '定时结束事件',
    'Error End Event': '错误结束事件',
    'Cancel End Event': '取消结束事件',
    'Compensation End Event': '补偿结束事件',
    'Signal End Event': '信号结束事件',
    'Terminate End Event': '终止结束事件',
    'Message Boundary Event': '消息边界事件',
    'Message Boundary Event (non-interrupting)': '消息边界事件（非中断）',
    'Timer Boundary Event': '定时边界事件',
    'Timer Boundary Event (non-interrupting)': '定时边界事件（非中断）',
    'Escalation Boundary Event': '升级边界事件',
    'Escalation Boundary Event (non-interrupting)': '升级边界事件（非中断）',
    'Conditional Boundary Event': '条件边界事件',
    'Conditional Boundary Event (non-interrupting)': '条件边界事件（非中断）',
    'Error Boundary Event': '错误边界事件',
    'Cancel Boundary Event': '取消边界事件',
    'Signal Boundary Event': '信号边界事件',
    'Signal Boundary Event (non-interrupting)': '信号边界事件（非中断）',
    'Compensation Boundary Event': '补偿边界事件',
    'Exclusive Gateway': '互斥网关',
    'Parallel Gateway': '并行网关',
    'Inclusive Gateway': '相容网关',
    'Complex Gateway': '复杂网关',
    'Event based Gateway': '事件网关',
    'Transaction': '转运',
    'Sub Process': '子流程',
    'Event Sub Process': '事件子流程',
    'Collapsed Pool': '折叠池',
    'Expanded Pool': '展开池',
    // Errors
    'no parent for {element} in {parent}': '在{parent}里，{element}没有父类',
    'no shape type specified': '没有指定的形状类型',
    'flow elements must be children of pools/participants': '流元素必须是池/参与者的子类',
    'out of bounds release': 'out of bounds release',
    'more than {count} child lanes': '子道大于{count} ',
    'element required': '元素不能为空',
    'diagram not part of bpmn:Definitions': '流程图不符合bpmn规范',
    'no diagram to display': '没有可展示的流程图',
    'no process or collaboration to display': '没有可展示的流程/协作',
    'element {element} referenced by {referenced}#{property} not yet drawn': '由{referenced}#{property}引用的{element}元素仍未绘制',
    'already rendered {element}': '{element} 已被渲染',
    'failed to import {element}': '导入{element}失败',
    // 属性面板的参数
    'Id': '标识',
    'Name': '名称',
    'General': '常规',
    'Details': '详情',
    'Message Name': '消息名称',
    'Message': '消息',
    'Initiator': '创建者',
    'Asynchronous Continuations': '持续异步',
    'Asynchronous Before': '异步前',
    'Asynchronous After': '异步后',
    'Job Configuration': '工作配置',
    'Exclusive': '排除',
    'Job Priority': '工作优先级',
    'Retry Time Cycle': '重试时间周期',
    'Documentation': '文档',
    'Element Documentation': '元素文档',
    'History Configuration': '历史配置',
    'History Time To Live': '历史的生存时间',
    'Forms': '表单',
    'Form Key': '表单key',
    'Form Fields': '表单字段',
    'Business Key': '业务key',
    'Form Field': '表单字段',
    'ID': '编号',
    'Type': '类型',
    'Label': '名称',
    'Default Value': '默认值',
    'Validation': '校验',
    'Add Constraint': '添加约束',
    'Config': '配置',
    'Properties': '属性',
    'Add Property': '添加属性',
    'Value': '值',
    'Listeners': '监听器',
    'Execution Listener': '执行监听',
    'Event Type': '事件类型',
    'Listener Type': '监听器类型',
    'Java Class': 'Java类',
    'Expression': '表达式',
    'Must provide a value': '必须提供一个值',
    'Delegate Expression': '代理表达式',
    'Script': '脚本',
    'Script Format': '脚本格式',
    'Script Type': '脚本类型',
    'Inline Script': '内联脚本',
    'External Script': '外部脚本',
    'Resource': '资源',
    'Field Injection': '字段注入',
    'Extensions': '扩展',
    'Input/Output': '输入/输出',
    'Input Parameters': '输入参数',
    'Output Parameters': '输出参数',
    'Parameters': '参数',
    'Output Parameter': '输出参数',
    'Timer Definition Type': '定时器定义类型',
    'Timer Definition': '定时器定义',
    'Date': '日期',
    'Duration': '持续',
    'Cycle': '循环',
    'Signal': '信号',
    'Signal Name': '信号名称',
    'Escalation': '升级',
    'Error': '错误',
    'Link Name': '链接名称',
    'Condition': '条件名称',
    'Variable Name': '变量名称',
    'Variable Event': '变量事件',
    'Specify more than one variable change event as a comma separated list.': '多个变量事件以逗号隔开',
    'Wait for Completion': '等待完成',
    'Activity Ref': '活动参考',
    'Version Tag': '版本标签',
    'Executable': '可执行文件',
    'External Task Configuration': '扩展任务配置',
    'Task Priority': '任务优先级',
    'External': '外部',
    'Connector': '连接器',
    'Must configure Connector': '必须配置连接器',
    'Connector Id': '连接器编号',
    'Implementation': '实现方式',
    'Field Injections': '字段注入',
    'Fields': '字段',
    'Result Variable': '结果变量',
    'Topic': '主题',
    'Configure Connector': '配置连接器',
    'Input Parameter': '输入参数',
    'Assignee': '代理人',
    'Candidate Users': '候选用户',
    'Candidate Groups': '候选组',
    'Due Date': '到期时间',
    'Follow Up Date': '跟踪日期',
    'Priority': '优先级',
    'The follow up date as an EL expression (e.g. ${someDate} or an ISO date (e.g. 2015-06-26T09:54:00)': '跟踪日期必须符合EL表达式，如： ${someDate} ,或者一个ISO标准日期，如：2015-06-26T09:54:00',
    'The due date as an EL expression (e.g. ${someDate} or an ISO date (e.g. 2015-06-26T09:54:00)': '跟踪日期必须符合EL表达式，如： ${someDate} ,或者一个ISO标准日期，如：2015-06-26T09:54:00',
    'Variables': '变量'
  }
  
export const NodeName = {
    'bpmn:Process': '流程',
    'bpmn:StartEvent': '开始事件',
    'bpmn:IntermediateThrowEvent': '中间事件',
    'bpmn:Task': '任务',
    'bpmn:SendTask': '抄送',
    'bpmn:ReceiveTask': '接收任务',
    'bpmn:UserTask': '用户任务',
    'bpmn:ManualTask': '手工任务',
    'bpmn:BusinessRuleTask': '业务规则任务',
    'bpmn:ServiceTask': '服务任务',
    'bpmn:ScriptTask': '脚本任务',
    'bpmn:EndEvent': '结束事件',
    'bpmn:SequenceFlow': '流程线',
    'bpmn:ExclusiveGateway': '互斥网关',
    'bpmn:ParallelGateway': '并行网关',
    'bpmn:InclusiveGateway': '相容网关',
    'bpmn:ComplexGateway': '复杂网关',
    'bpmn:EventBasedGateway': '事件网关'
}

export const newTrans:any = {
  "Name":"名称",
  "Value":"值",
  "ID":"唯一标识(ID)",
  "General":"基础属性",
  'Activate hand tool': '启动抓手工具',
  'Activate lasso tool': '启动套索工具',
  "Activate create/remove space tool": "启动创建/删除空间工具",
  "Activate global connect tool": "启动全局连接工具",
  "Ad-hoc": "Ad-hoc子流程",
  "Add lane above": "添加到通道之上",
  "Add lane below": "添加到通道之下",
  "Append text annotation":'添加文本注释',
  "Append ConditionIntermediateCatchEvent": "添加中间条件捕获事件",
  "Append element": "添加元素",
  "Append end event": "添加结束事件",
  "Append gateway": "添加网关",
  "Append intermediate/boundary event": "添加中间/边界事件",
  "Append MessageIntermediateCatchEvent": "添加消息中间捕获事件",
  "Append ReceiveTask": "添加接收任务",
  "Append SignalIntermediateCatchEvent": "添加信号中间捕获事件",
  "Append task": "添加任务",
  "Append TimerIntermediateCatchEvent": "添加定时器中间捕获事件",
  "Append compensation activity": "追加补偿活动",
  "Append {type}": "追加 {type}",
  "Boundary Event": "边界事件",
  "Business Rule Task": "规则任务",
  "Call Activity": "引用流程",
  "Cancel Boundary Event": "取消边界事件",
  "Cancel End Event": "取消结束事件",
  "Change type": "更改类型",
  "Collapsed Pool": "折叠池",
  "Collection": "集合",
  "Compensation Boundary Event": "补偿边界事件",
  "Compensation End Event": "结束补偿事件",
  "Compensation Intermediate Throw Event": "中间补偿抛出事件",
  "Compensation Start Event": "补偿启动事件",
  "Complex gateway": "复杂网关",
  "Conditional Boundary Event": "条件边界事件",
  "Conditional Boundary Event (non-interrupting)": "条件边界事件 (非中断)",
  "Conditional Flow": "条件流",
  "Conditional Intermediate Catch Event": "中间条件捕获事件",
  "Conditional Start Event": "条件启动事件",
  "Conditional Start Event (non-interrupting)": "条件启动事件 (非中断)",
  "Connect using Association": "文本关联",
  "Connect using data input association": "数据关联",
  "Connect using sequence/message flow or association":"消息关联",

  "Create intermediateThrowEvent/boundary event": "创建中间抛出/边界事件",
  "Create data object reference": "创建数据对象引用",
  "Create data store reference": "创建数据存储引用",
  "Create element": "创建元素",
  "Create end event": "创建结束事件",
  "Create gateway": "创建网关",
  "Create group": "创建组",
  "Create intermediate/boundary event": "创建中间/边界事件",
  "Create pool/participant": "创建池/参与者",
  "Create start event": "创建开始事件",
  "Create task": "创建任务",
  "Create expanded sub-process": "创建可折叠子流程",
  "Create {type}": "创建 {type}",
  "Data": "数据",
  "Data Object Reference": "数据对象引用",
  "Data Store Reference": "数据存储引用",
  "Default Flow": "默认流",
  "Divide into three lanes": "分成三条通道",
  "Divide into two lanes": "分成两条通道",
  "Empty Pool": "空泳道",
  "Empty Pool (removes content)": "清空泳道（删除内容）",
  "End Event": "结束事件",
  "Error Boundary Event": "错误边界事件",
  "Error End Event": "结束错误事件",
  "Error Start Event": "错误启动事件",
  "Escalation Boundary Event": "升级边界事件",
  "Escalation Boundary Event (non-interrupting)": "升级边界事件 (非中断)",
  "Escalation End Event": "结束升级事件",
  "Escalation Intermediate Throw Event": "中间升级抛出事件",
  "Escalation Start Event": "升级启动事件",
  "Escalation Start Event (non-interrupting)": "升级启动事件 (非中断)",
  "Events": "事件",
  "Event Sub Process": "事件子流程",
  "Event based Gateway": "事件网关",
  "Exclusive Gateway": "独占网关",
  "Expanded Pool": "展开泳道",
  "Gateways": "网关",
  "Inclusive Gateway": "包容网关",
  "Intermediate Throw Event": "中间抛出事件",
  "Link Intermediate Catch Event": "中间链接捕获事件",
  "Link Intermediate Throw Event": "中间链接抛出事件",
  "Loop": "循环",
  "Manual Task": "手动任务",
  "Message Boundary Event": "消息边界事件",
  "Message Boundary Event (non-interrupting)": "消息边界事件 (非中断)",
  "Message End Event": "结束消息事件",
  "Message Intermediate Catch Event": "中间消息捕获事件",
  "Message Intermediate Throw Event": "中间消息抛出事件",
  "Message Start Event": "消息启动事件",
  "Message Start Event (non-interrupting)": "消息启动事件 (非中断)",
  "Parallel Gateway": "并行网关",
  "Parallel Multi Instance": "并行多实例",
  "Participants": "参与者",
  "Participant Multiplicity": "参与者多重性",
  "Receive Task": "接受任务",
  "Remove": "移除",
  "Script Task": "脚本任务",
  "Send task": "发送任务",
  "Sequence Flow": "顺序流",
  "Sequential Multi Instance": "串行多实例",
  "Service Task": "服务任务",
  "Signal Boundary Event": "信号边界事件",
  "Signal Boundary Event (non-interrupting)": "信号边界事件 (非中断)",
  "Signal End Event": "结束信号事件",
  "Signal Intermediate Catch Event": "中间信号捕获事件",
  "Signal Intermediate Throw Event": "中间信号抛出事件",
  "Signal Start Event": "信号启动事件",
  "Signal Start Event (non-interrupting)": "信号启动事件 (非中断)",
  "Start Event": "开始事件",
  "Sub Process": "子流程",
  "Sub Processes": "子流程",
  "Sub Process (collapsed)": "可折叠子流程",
  "Sub Process (expanded)": "可展开子流程",
  "Task": "任务",
  "Tasks": "任务",
  "Terminate End Event": "终止边界事件",
  "Timer Boundary Event": "定时边界事件",
  "Timer Boundary Event (non-interrupting)": "定时边界事件 (非中断)",
  "Timer Intermediate Catch Event": "中间定时捕获事件",
  "Timer Start Event": "定时启动事件",
  "Timer Start Event (non-interrupting)": "定时启动事件 (非中断)",
  "Transaction": "事务",
  "User Task": "用户任务",
  "User task": "用户任务",
  "already rendered {element}": "{element} 已呈现",
  "diagram not part of bpmn:Definitions": "图表不是 bpmn:Definitions 的一部分",
  "element required": "需要元素",
  "correcting missing bpmnElement on {plane} to {rootElement}": "在 {plane} 上更正缺失的 bpmnElement 为 {rootElement}",
  "element {element} referenced by {referenced}#{property} not yet drawn": "元素 {element} 的引用 {referenced}#{property} 尚未绘制",
  "failed to import {element}": "{element} 导入失败",
  "flow elements must be children of pools/participants": "元素必须是池/参与者的子级",
  "more than {count} child lanes": "超过 {count} 条通道",
  "missing {semantic}#attachedToRef": "在 {element} 中缺少 {semantic}#attachedToRef",
  "multiple DI elements defined for {element}": "为 {element} 定义了多个 DI 元素",
  "no bpmnElement referenced in {element}": "{element} 中没有引用 bpmnElement",
  "no diagram to display": "没有要显示的图表",
  "no shape type specified": "未指定形状类型",
  "no parent for {element} in {parent}": "在 {element} 中没有父元素 {parent}",
  "no process or collaboration to display": "没有可显示的流程或协作",
  "out of bounds release": "越界释放",
  "Version tag":"版本标记",
  "Change element":"改变元素",
  "Documentation":"文档",
  "PROCESS":"流程",
  "Element documentation":"元素文档说明",
  "User assignment":"分配用户",
  "History cleanup":"历史记录清理",
  "Time to live":"历史记录生存时间",
  "Tasklist":"任务列表",
  "Candidate starter":"候选启动器",
  "Candidate starter groups":"候选启动组",
  "Specify more than one group as a comma separated list.":"多个组用','分隔.",
  "Candidate starter users":"候选发起人",
  "Specify more than one user as a comma separated list.":"多个用户用','分隔.",
  "External task":"外部任务",
  "Startable":"可启动(Startable)",
  "Executable":"可直接执行",
  "Job execution":"作业执行",
  "Priority":"优先级",
  "Forms":"表单",
  "Execution listeners":"执行侦听器",
  "Extension properties":"扩展属性",
  "Event type":"事件类型",
  "Listener type":"侦听器类型",
  "Field injection":"字段注入",
  "Start initiator":"开始发起人",
  "Initiator":"发起人",
  "Asynchronous continuations":"异步延续",
  "Before":"之前",
  "After":"之后",
  "Inputs":"输入",
  "Outputs":"输出",
  "Local variable name":"局部变量名称",
  "Assignment type":"分配类型",
  "Format":"格式",
  "Type":"类型",
  "Expression":"表达式(Expression)",
  "Script":"脚本(Script)",
  "Delegate expression":"委托表达式(Delegate expression)",
  "Java class":"Java类(Java class)",
  "start":"开始(start)",
  "end":"结束(end)",
  "Start typing \"${}\" to create an expression.":"开始键入\"${}\"以创建表达式.",
  "Process variable name":"过程变量名称",
  "List values":"列表值",
  "Map entries":"映射条目",
  "Key":"键",
  "Values":"值",
  "Form reference":"引用表单ID",
  "Binding":"结合",
  "Version":"版本",
  "Form fields":"表单字段",
  "Form key":"表单ID",
  "Embedded or External Task Forms":"拓展表单",
  "Camunda Forms":"标准表单",
  "Generated Task Forms":"内置表单",
  "Refers to the process variable name":"指的是(引用)过程变量名称",
  "Label":"标签",
  "Default value":"默认值",
  "Constraints":"限制",
  "Properties":"属性",
  "Config":"配置",
  "Implementation":"实施",
  "Field injections":"字段注入",
  "Task listeners":"任务侦听器",
  "Listener ID":"侦听器ID",
  "Message":"消息",
  "Global message reference":"引用全局消息ID",
  "Result variable":"结果变量",
  "Resource":"资源",
  "External resource":"外部资源",
  "Inline script":"内联脚本",
  "Process variables":"过程变量",
  "Global signal reference":"引用全局信号ID",
  "Signal":"信号",
  "Called element":"被调用元素",
  "In mapping propagation":"在映射传播中",
  "Propagate all variables":"传播所有变量",
  "Out mapping propagation":"向外映射传播",
  "In mappings":"在映射中",
  "Source":"来源",
  "Target":"目标",
  "Local":"局部的(Local)",
  "Out mappings":"输出映射",
  "Link":"链接",
  "Timer":"定时器",
  "Retry time cycle":"重试时间周期",
  "Variable name":"变量名称",
  "Condition Expression":"条件表达式",
  "Condition":"条件",
  "Process documentation":"流程文档",
  "Assignee":"委托人",
  "Candidate groups":"候选组",
  "Candidate users":"候选用户",
  "Due date":"期限",
  "The due date as an EL expression (e.g. ${someDate}) or an ISO date (e.g. 2015-06-26T09:54:00).":"到期日期为EL表达式(例如${someDate})或ISO日期(例如2015-06-26T09:54:00)",
  "Follow up date":"跟进日期",
  "The follow up date as an EL expression (e.g. ${someDate}) or an ISO date (e.g. 2015-06-26T09:54:00).":"作为EL表达式(例如${someDate})或ISO日期(例如2015-06-26T09:54:00)的跟进日期",
  "Connector ID":"连接器ID",
  "Connector inputs":"连接器输入",
  "Connector outputs":"连接器输出",
  "Topic":"主题",
  "Errors":"错误",
  "Global error reference":"引用全局错误ID",
  "Throw expression":"Throw表达式",
  "Decision reference":"引用决策ID",
  "Tenant ID":"租户ID",
  "Multi-instance":"多实例",
  "Loop cardinality":"循环基数",
  "Completion condition":"完成条件",
  "Element variable":"元素变量",
  "Asynchronous before":"异步之前",
  "Asynchronous after":"异步之后",
}